[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "cairo", "pango", "gdk-pixbuf", "libffi", "pkg-config"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]
